### ISSUE TITLE
获取文档信息的时候出现错误

### ISSUE THREAD

**Issue by JunjieLink** [duanyifei/mayiwenku#1]
Python3.5按照`requirements.txt`的内容安装了所有库。
```
Successfully installed Pillow-5.3.0 Pygments-2.2.0 certifi-2018.11.29 chardet-3.0.4 colorama-0.3.9 decorator-4.3.0 idna-2.8 ipython-6.5.0 ipython-genutils-0.2.0 jedi-0.12.1 numpy-1.15.1 parso-0.3.1 pickleshare-0.7.4 prompt-toolkit-1.0.15 reportlab-3.5.12 requests-2.21.0 scipy-1.1.0 simplegeneric-0.8.1 six-1.11.0 traitlets-4.3.2 urllib3-1.24.1 wcwidth-0.1.7 win-unicode-console-0.5
```
然后运行的时候，出现了错误：
```
>>> python mayiwenku.py --url=http://www.mayiwenku.com/p-3169923.html
>>> Traceback (most recent call last):
  File "R:\mayiwenku-master\mayiwenku.py", line 184, in main
    try:
  File "R:\mayiwenku-master\mayiwenku.py", line 137, in get_document
    # 获取文档基本信息
  File "R:\mayiwenku-master\mayiwenku.py", line 125, in get_document_info
    #
NameError: name 're' is not defined
```
请教一下是什么问题？

**Comment by jimchou800** [comment]
同样的问题

**Comment by jimchou800** [comment]
抱着试试的心态，在github页面自带的编辑器打开mayiwenku.py文件，然后覆盖本地clone的，再git status发现有变化。猜测有不可见字符的影响，然后 git diff 果然是
`
+# coding:utf8^M                                                                 +import re^M                                                                     +import os^M                                                                     +import time^M                                                                   +import argparse^M                                                               +import traceback^M                                                              +^M                                                                              +import requests^M                                                               +from reportlab.platypus import SimpleDocTemplate, Image, PageBreak^M            +from reportlab.lib.pagesizes import A4, landscape^M
`
^M 是window的换行符CRLF

估计是git clone发生了换行符的转换，在window环境python要用CRLF 换行符


@JunjieLink @duanyifei 非常感谢作者的贡献

**Comment by thgpddl** [comment]
@jimchou800 正解，所以解决办法是在Windows下使用sublime打开，选中全部代码，点击“视图”-“行结束符”-选中“Windows换行符”，然后保存即可成功运行。亲测可行
